{"error": "Traceback (most recent call last):\n  File \"/Users/neilaspin/Downloads/aichallenge/tools/engine.py\", line 93, in run_game\n    sandbox.start(bot_cmd)\n  File \"/Users/neilaspin/Downloads/aichallenge/tools/sandbox.py\", line 378, in start\n    self.command_process = subprocess.Popen(shell_command,\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py\", line 951, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py\", line 1691, in _execute_child\n    executable = args[0]\nIndexError: list index out of range\n", "playernames": [null, "TestBot.py"]}